name: Update Major Version Tag

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  update-major-version-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Update Major Version Tag
        run: |
          TAG_REF=${GITHUB_REF#refs/tags/}
          MAJOR_VERSION=$(echo ${TAG_REF} | cut -d. -f1)
          MAJOR_TAG="v$MAJOR_VERSION"

          if git rev-parse "$MAJOR_TAG" >/dev/null 2>&1
          then
              echo "Updating existing major version tag: $MAJOR_TAG"
              git tag -d $MAJOR_TAG
              git push origin :refs/tags/$MAJOR_TAG
          else
              echo "Creating new major version tag: $MAJOR_TAG"
          fi

          git tag $MAJOR_TAG $TAG_REF
          git push origin $MAJOR_TAG